AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CloudProject

  Sample SAM Template for CloudProject

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true
  UsersTable:
    Type: String
    Description: Users Table Name
    Default: Cloud_Users
  JWTSecret:
    Type: String
    Description: JWT Secret
    NoEcho: true
    Default: "cummies"
  ConnectionsTable:
    Type: String
    Description: WebSocket Connections Table Name
    Default: WebSocketConnections

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        JWT_SECRET: !Ref JWTSecret
        CONNECTIONS_TABLE: !Ref ConnectionsTable
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'300'"
        AllowCredentials: true
  RegisterUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: register.lambda_handler
      Runtime: python3.12
      Timeout: 100
      Architectures:
      - x86_64
      Layers:
        - !Ref BcryptLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /users/register
            Method: post
  RegisterOptionsUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: register.lambda_handler
      Runtime: python3.12
      Timeout: 100
      Architectures:
      - x86_64
      Layers:
        - !Ref BcryptLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /users/register
            Method: options

  LoginUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: login.lambda_handler
      Runtime: python3.12
      Timeout: 100
      Architectures:
      - x86_64
      Layers:
        - !Ref BcryptLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/login
            Method: post
  LoginOptionsUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/
      Handler: login.lambda_handler
      Runtime: python3.12
      Timeout: 100
      Architectures:
      - x86_64
      Layers:
        - !Ref BcryptLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/login
            Method: options
            
  PutUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: users/
      Handler: put.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        PutUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: put
  DeleteUser:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: users/
      Handler: delete.lambda_handler
      Runtime: python3.12
      Architectures:
      - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        DeleteUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: delete

  BcryptLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: bcrypt-layer
      Description: Layer containing bcrypt library
      ContentUri: bcrypt_layer/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12

  # LOBBY ENDPOINTS

  CreateLobby:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lobbies/
      Handler: create.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        CreateLobby:
          Type: Api
          Properties:
            Path: /lobbies
            Method: post

  ListLobbies:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lobbies/
      Handler: list.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ListLobbies:
          Type: Api
          Properties:
            Path: /lobbies
            Method: get

  GetLobbyDetails:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lobbies/
      Handler: getdetails.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        GetLobbyDetails:
          Type: Api
          Properties:
            Path: /lobbies/{lobbyId}
            Method: get

  JoinLobby:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lobbies/
      Handler: join.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        JoinLobby:
          Type: Api
          Properties:
            Path: /lobbies/{lobbyId}/join
            Method: post

  LeaveLobby:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lobbies/
      Handler: leave.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        LeaveLobby:
          Type: Api
          Properties:
            Path: /lobbies/{lobbyId}/leave
            Method: post

  DeleteLobby:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lobbies/
      Handler: delete.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        DeleteLobby:
          Type: Api
          Properties:
            Path: /lobbies/{lobbyId}
            Method: delete


  AIEvaluationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ai/
      Handler: evaluate.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /ai/evaluate
            Method: post          

  # WEBSOCKET ENDPOINTS
  # WebSocket API
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: GameWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  # WebSocket Deployment
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - WebSocketConnectRoute
      - WebSocketDisconnectRoute
      - WebSocketDefaultRoute
    Properties:
      ApiId: !Ref WebSocketApi

  # WebSocket Stage
  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref WebSocketApi

  # WebSocket Lambda Functions
  WebSocketConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websocket/
      Handler: connect.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable

  WebSocketDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websocket/
      Handler: disconnect.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable

  WebSocketDefaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: websocket/
      Handler: default.lambda_handler
      Runtime: python3.12
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ConnectionsTable
        - Statement:
            - Effect: Allow
              Action:
                - 'execute-api:ManageConnections'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*'
      Environment:
        Variables:
          TABLE_NAME: !Ref ConnectionsTable

  # WebSocket Routes
  WebSocketConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketConnectInteg

  WebSocketConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketConnectFunction.Arn}/invocations

  WebSocketDisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketDisconnectInteg

  WebSocketDisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDisconnectFunction.Arn}/invocations

  WebSocketDefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      AuthorizationType: NONE
      OperationName: DefaultRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WebSocketDefaultInteg

  WebSocketDefaultInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      Description: Default Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebSocketDefaultFunction.Arn}/invocations


  WebSocketConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ConnectionsTable
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  LobbiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Lobbies
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda permissions
  WebSocketConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
      - WebSocketConnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketConnectFunction
      Principal: apigateway.amazonaws.com

  WebSocketDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
      - WebSocketDisconnectFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDisconnectFunction
      Principal: apigateway.amazonaws.com

  WebSocketDefaultPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocketApi
      - WebSocketDefaultFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref WebSocketDefaultFunction
      Principal: apigateway.amazonaws.com

Outputs:
  AIEvaluationFunction:
    Description: "AI Evaluation Lambda Function ARN"
    Value: !GetAtt AIEvaluationFunction.Arn
  AIEvaluationFunctionIamRole:
    Description: "AI Evaluation Lambda Function IAM Role"
    Value: !GetAtt AIEvaluationFunctionRole.Arn
  ApiGatewayApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WebSocketApiEndpoint:
    Description: "WebSocket API endpoint"
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/${WebSocketStage}"